services:
  frontend:
    image: ""
    build:
      context: https://github.com/SciCatProject/frontend.git#master      
      pull: true 
      no_cache: true 
    environment:
      GITHUB_REPO: https://github.com/SciCatProject/frontend.git#master
    volumes:
      - frontend_jobs_dev:${WORKDIR:-/home/node/app}

