services:
  backend:
    user: root
    build:
      context:
        https://github.com/SciCatProject/scicat-backend-next.git#master
    environment:
      GITHUB_REPO:
        https://github.com/SciCatProject/scicat-backend-next.git#master
    env_file:
      - ./config/.jobs.env
    volumes:
      - v4_jobs_dev:${WORKDIR:-/home/node/app}
      - ./config/jobConfig.yaml:${WORKDIR:-/home/node/app}/jobConfig.yaml
      - ${DEV:+}./config/jobConfig.dev.yaml:${WORKDIR:-/home/node/app}/jobConfig.yaml
volumes:
  v4_jobs_dev:
    driver: local
